export const SET_CATEGORY = "SET_CATEGORY";
export const SET_CHANNEL_LIST = "SET_CHANNEL_LIST";
export const SET_ALL_VIDEOS = "SET_ALL_VIDEOS";
export const SET_VIDEO = "SET_VIDEO";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOADING_CATEGORIES = "LOADING_CATEGORIES";
